server:
    port: 8080
    contextPath: /bootlab
    
spring:
    profiles:
        active: local
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://db.dledu.dingli:3306/test?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8
        databaseName:
        serverName:
        username: root
        password: pwd
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true